debootstrap --variant=minbase

diff --git a/rootfs/lowerdir/usr/bin/sensible-editor b/rootfs/lowerdir/usr/bin/sensible-editor
--- a/rootfs/lowerdir/usr/bin/sensible-editor
+++ b/rootfs/lowerdir/usr/bin/sensible-editor
@@ -1,65 +1,44 @@
 #!/bin/sh
-# Copyright 2007 Jari Aalto;
-# Copyright 2019-2022 Bastien Roucariès
-# Copyright 2022 Richard Lewis
-# Released under GNU GPL v2 or any later version
-PATH="$PATH:/usr/share/sensible-utils/bin"
 
-program="$(realpath "$(command -v "$0")")"
+ret="$?"
 
-Try()
-{
-    $candidate "$@"
-    ret=$?
-    [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ] && exit "$ret"
-}
+# Prevent recursive loops, where these values are set to this script
+p="$(which sensible-editor)"
+[ -n "$EDITOR" ] && [ "$(which $EDITOR || true)" = "$p" ] && EDITOR=
+[ -n "$EDITOR" ] && [ "$(which $VISUAL || true)" = "$p" ] && VISUAL=
+[ -n "$EDITOR" ] && [ "$(which $SELECTED_EDITOR || true)" = "$p" ] && SELECTED_EDITOR=
 
-TryEnv()
-{
-    # global $candidate
-    [ -z "$candidate" ] && return
-    # Prevent recursive loops, where environment variables are set to this script
-    [ x$(realpath "$(command -v "$candidate" || true)" || true) = x"$program" ] && return
-    # interpret like environ (7) man page. Do not use eval in order to not leak variables
-    sh -c "$candidate \"\$@\"" EDITOR "$@"
-    ret=$?
-    # Operating system command not found
-    [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ] && exit "$ret"
-}
-
-
-# work around for #991982
-nano ()
-{
-    if [ -z "$TERM" ]; then
-	return 126
-    else
-	command nano "$@"
-    fi
-}
-
-for candidate in "$VISUAL" "$EDITOR" "$SENSIBLE_EDITOR" "$SELECTED_EDITOR"; do
-    TryEnv "$@"
-done
-
-# fix #987675
-if [ -n "$HOME" ]; then
-    if [ -r ~/.selected_editor ]; then
-	. ~/.selected_editor 2>/dev/null
-    elif [ -z "$EDITOR" ] && [ -z "$SELECTED_EDITOR" ] && [ -t 0 ]; then
-	select-editor && . ~/.selected_editor 2>/dev/null
-    fi
+if [ -n "$VISUAL" ]; then
+	${VISUAL} "$@"
+	ret="$?"
+	if [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ]; then
+		exit "$ret"
+	fi
 fi
 
-for candidate in "$EDITOR" "$SELECTED_EDITOR"; do
-    TryEnv "$@"
-done
+if [ -r ~/.selected_editor ]; then
+	. ~/.selected_editor 2>/dev/null || true
+elif [ -z "$EDITOR" ] && [ -z "$SELECTED_EDITOR" ] && [ -t 0 ]; then
+	select-editor && . ~/.selected_editor 2>/dev/null || true
+fi
 
-for candidate in editor nano nano-tiny vi; do
-    Try "$@"
-done
-
-echo "Couldn't find an editor!" 1>&2
-echo 'Set the $EDITOR environment variable to your desired editor.' 1>&2
-exit 1
-
+${EDITOR:-${SELECTED_EDITOR:-editor}} "$@"
+ret="$?"
+if [ "$ret" -eq 126 ] || [ "$ret" -eq 127 ]; then
+	nano "$@"
+	ret="$?"
+	if [ "$ret" -eq 126 ] || [ "$ret" -eq 127 ]; then
+		nano-tiny "$@"
+		ret="$?"
+		if [ "$ret" -eq 126 ] || [ "$ret" -eq 127 ]; then
+			vi "$@"
+			ret="$?"
+			if [ "$ret" -eq 126 ] || [ "$ret" -eq 127 ]; then
+				echo "Couldn't find an editor!" 1>&2
+				echo "Set the \$EDITOR environment variable to your desired editor." 1>&2
+				exit 1
+			fi
+		fi
+	fi
+fi
+exit "$ret"
diff --git a/rootfs/lowerdir/usr/bin/sensible-pager b/rootfs/lowerdir/usr/bin/sensible-pager
--- a/rootfs/lowerdir/usr/bin/sensible-pager
+++ b/rootfs/lowerdir/usr/bin/sensible-pager
@@ -1,28 +1,17 @@
 #!/bin/sh
-# Copyright 2007 Jari Aalto; Released under GNU GPL v2 or any later version
-PATH="$PATH:/usr/share/sensible-utils/bin"
 
 # Prevent recursive loops, where these values are set to this script
-program="$(realpath "$(command -v "$0")")"
+p="$(which sensible-pager)"
+[ -n "$PAGER" ] && [ "$(which $PAGER || true)" = "$p" ] && PAGER=
 
-TryEnv()
-{
-    # global $candidate
-    [ -z "$candidate" ] && return
-    # Prevent recursive loops, where environment variables are set to this script
-    [ x$(realpath "$(command -v "$candidate" || true)" || true) = x"$program" ] && return
-    # interpret like environ (7) man page. Do not use eval in order to not leak variables
-    sh -c "$candidate \"\$@\"" PAGER "$@"
-    ret=$?
-    # Operating system command not found
-    [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ] && exit "$ret"
-}
-
-for candidate in "$PAGER" "$SENSIBLE_PAGER" pager more; do
-    TryEnv "$@"
-done
-
-
-echo "Couldn't find a pager!" 1>&2
-echo 'Set the $PAGER environment variable to your desired pager.'
-exit 1
+${PAGER:-pager} "$@"
+ret="$?"
+if [ "$ret" -eq 126 ] || [ "$ret" -eq 127 ]; then
+more "$@"
+ret="$?"
+	if [ "$ret" -eq 126 ] || [ "$ret" -eq 127 ]; then
+		echo "Couldn't find a pager!" 1>&2
+		echo "Set the \$PAGER environment variable to your desired pager." 1>&2
+		exit 1
+	fi
+fi
diff --git a/rootfs/lowerdir/usr/lib/lsb/init-functions b/rootfs/lowerdir/usr/lib/lsb/init-functions
--- a/rootfs/lowerdir/usr/lib/lsb/init-functions
+++ b/rootfs/lowerdir/usr/lib/lsb/init-functions
@@ -144,7 +144,8 @@ killproc () {
         name_param="--name $base --pidfile $pidfile"
     fi
 
-    sig=${2:-} sig=${sig#-} sig=${sig#SIG}
+    sig=$(echo ${2:-} | sed -e 's/^-\(.*\)/\1/')
+    sig=$(echo $sig | sed -e 's/^SIG\(.*\)/\1/')
     if [ "$sig" = 15 ] || [ "$sig" = TERM ]; then
         is_term_sig="terminate_signal"
     fi
@@ -209,13 +210,18 @@ status_of_proc () {
 }
 
 log_use_fancy_output () {
+    TPUT=/usr/bin/tput
+    EXPR=/usr/bin/expr
     if  [ -t 1 ] &&
 	[ "x${TERM:-}" != "x" ] &&
-	[ "x${TERM:-}" != "xdumb" ]
+	[ "x${TERM:-}" != "xdumb" ] &&
+	[ -x $TPUT ] && [ -x $EXPR ] &&
+	$TPUT hpa 60 >/dev/null 2>&1 &&
+	$TPUT setaf 1 >/dev/null 2>&1
     then
-        [ -z $FANCYTTY ] && return 0 || true
+        [ -z $FANCYTTY ] && FANCYTTY=1 || true
     else
-        return 1
+        FANCYTTY=0
     fi
     case "$FANCYTTY" in
         1|Y|yes|true)   true;;
@@ -225,21 +231,21 @@ log_use_fancy_output () {
 
 log_success_msg () {
     if [ -n "${1:-}" ]; then
-        log_begin_msg "$@"
+        log_begin_msg $@
     fi
     log_end_msg 0
 }
 
 log_failure_msg () {
     if [ -n "${1:-}" ]; then
-        log_begin_msg "$@" "..."
+        log_begin_msg $@ "..."
     fi
     log_end_msg 1 || true
 }
 
 log_warning_msg () {
     if [ -n "${1:-}" ]; then
-        log_begin_msg "$@" "..."
+        log_begin_msg $@ "..."
     fi
     log_end_msg 255 || true
 }
@@ -337,27 +343,32 @@ log_end_msg () {
         return 1
     fi
 
+    local retval
+    retval=$1
+
     log_end_msg_pre "$@"
 
     # Only do the fancy stuff if we have an appropriate terminal
+    # and if /usr is already mounted
     if log_use_fancy_output; then
-        esc=''		# escape character, printf '\033'
-        red="$esc[31m"		# ANSI color escapes
-        yellow="$esc[33m"
-        normal="$esc[0m"
+        RED=$( $TPUT setaf 1)
+        YELLOW=$( $TPUT setaf 3)
+        NORMAL=$( $TPUT op)
     else
-        red= yellow= normal=
+        RED=''
+        YELLOW=''
+        NORMAL=''
     fi
 
     if [ $1 -eq 0 ]; then
         echo "." || true
     elif [ $1 -eq 255 ]; then
-        echo " ${yellow}(warning).${normal}" || true
+        /bin/echo -e " ${YELLOW}(warning).${NORMAL}" || true
     else
-        echo " ${red}failed!${normal}" || true
+        /bin/echo -e " ${RED}failed!${NORMAL}" || true
     fi
     log_end_msg_post "$@"
-    return $1
+    return $retval
 }
 
 log_action_msg () {
@@ -389,10 +400,9 @@ log_action_end_msg () {
         echo "done${end}" || true
     else
         if log_use_fancy_output; then
-            esc=''		# escape character, printf '\033'
-            red="$esc[31m"	# ANSI color escapes
-            normal="$esc[0m"
-            echo "${red}failed${end}${normal}" || true
+            RED=$( $TPUT setaf 1)
+            NORMAL=$( $TPUT op)
+            /bin/echo -e "${RED}failed${end}${NORMAL}" || true
         else
             echo "failed${end}" || true
         fi
diff --git a/rootfs/lowerdir/var/lib/dpkg/info/libc6:amd64.preinst b/rootfs/lowerdir/var/lib/dpkg/info/libc6:amd64.preinst
--- a/rootfs/lowerdir/var/lib/dpkg/info/libc6:amd64.preinst
+++ b/rootfs/lowerdir/var/lib/dpkg/info/libc6:amd64.preinst
@@ -1,15 +1,100 @@
 #!/bin/sh
 set -e
+export LC_ALL=C
 
 type=$1
 preversion=$2
 
-kernel_compare_versions () {
+linux_compare_versions () {
+    verA=$(($(echo "$1" | sed 's/^\([0-9]*\.[0-9]*\)\([^.0-9]\|$\)/\1.0\2/; s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1 \* 10000 + \2 \* 100 + \3/')))
+    verB=$(($(echo "$3" | sed 's/^\([0-9]*\.[0-9]*\)\([^.0-9]\|$\)/\1.0\2/; s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1 \* 10000 + \2 \* 100 + \3/')))
+
+    test $verA -$2 $verB
+}
+
+kfreebsd_compare_versions () {
     verA=$(($(echo "$1" | sed 's/\([0-9]*\)\.\([0-9]*\).*/\1 \* 100 + \2/')))
     verB=$(($(echo "$3" | sed 's/\([0-9]*\)\.\([0-9]*\).*/\1 \* 100 + \2/')))
 
     test $verA -$2 $verB
 }
+
+# Sanity check.
+# If there are versions of glibc outside of the normal installation
+# location (/lib, /lib64, etc.) then things may break very badly
+# as soon as ld.so is replaced by a new version.  This check is not
+# foolproof, but it's pretty accurate.  This script ignores libraries
+# with different sonames, and libraries incompatible with the 
+# to-be-installed ld.so.
+check_dir () {
+    msg=$1
+    dir=$2
+
+    # Follow symlinks
+    dir=$(readlink -e $dir || true)
+
+    # Ignore inexistent directories
+    if ! test -d "$dir" ; then
+        return
+    fi
+  
+    # Detect possible candidates
+    files=$(ls $dir | egrep '^(ld|lib(d|c|m|pthread|rt|dl))-2.*.so' 2>/dev/null || true)
+    if test -z "$files" ; then
+        return
+    fi
+  
+    for file in $files ; do
+        lib=$dir/$file
+
+        # Skip if it is a symlink (as installed by lsb-core)
+        if test -L "$lib" ; then
+            continue
+        fi
+
+        # Skip if it is the currently dynamic loader
+        if test "$lib" = "$ldfile" ; then
+            continue
+        fi
+
+        # See if the found libraries are compatible with the system ld.so;
+        # if they aren't, they'll be ignored. Check e_ident, e_type (which
+        # will just be ET_DYN), and e_machine. If a match is found, there
+        # is a risk of breakage.
+        libbytes=`head -c 20 $lib | od -c`
+        if test "$ldbytes" != "$libbytes" ; then 
+          continue
+        fi
+
+        # Binaries owned packages are considered to do the right thing
+        # First try a quick lookup which should catch all cases on a 
+        # normal system
+        if echo $libcfiles | grep -q "[ ^]$lib[ $]" ; then 
+            continue
+        fi
+
+        # Slower lookup to confirm
+        if dpkg-query -S "$lib" >/dev/null 2>&1 ; then
+            continue
+        fi
+
+        # Output an error message and exit
+        echo
+        echo "A copy of the C library was found $msg:"
+        echo "  '$lib'"
+        echo "It is not safe to upgrade the C library in this situation;"
+        echo "please remove that copy of the C library or get it out of"
+        echo "'$dir' and try again."
+        echo
+        exit 1
+    done
+}
+
+if [ -n "$preversion" ] && dpkg --compare-versions "$preversion" lt 2.31-0ubuntu2; then
+	LCONFIG_NOTRIGGER=y
+	export LDCONFIG_NOTRIGGER
+	ldconfig || ldconfig --verbose
+fi
 
 if [ "$type" != abort-upgrade ]
 then
@@ -18,13 +103,7 @@ then
        ( [ "$DEBCONF_USE_CDEBCONF" ] || perl -e "" 2>/dev/null ) ; then
         . /usr/share/debconf/confmodule
         USE_DEBCONF=1
-    else
-        USE_DEBCONF=
     fi
-
-    # Only change LC_ALL after loading debconf to ensure the debconf templates
-    # are properly localized.
-    export LC_ALL=C
 
     # See if LD_LIBRARY_PATH contains the traditional /lib, but not the
     # multiarch path
@@ -55,6 +134,21 @@ then
     system=`uname -s`
     if [ "$system" = "Linux" ]
     then
+        # Test to make sure z < 255, in x.y.z-n form of kernel version
+        # Also make sure we don't trip on x.y.zFOO-n form
+        kernel_rev=$(uname -r | sed 's/\([0-9]*\.\)\{1,2\}\([0-9]*\)\(.*\)/\2/')
+        if [ "$kernel_rev" -ge 255 ]
+        then
+            echo "ERROR: Your kernel version indicates a revision number"
+            echo "of 255 or greater.  Glibc has a number of built in"
+            echo "assumptions that this revision number is less than 255."
+            echo "If you\'ve built your own kernel, please make sure that any"
+            echo "custom version numbers are appended to the upstream"
+            echo "kernel number with a dash or some other delimiter."
+            echo
+            exit 1
+        fi
+
         # sanity checking for the appropriate kernel on each architecture.
         kernel_ver=`uname -r`
         case ${DPKG_MAINTSCRIPT_ARCH} in
@@ -65,7 +159,7 @@ then
                 ;;
         esac
 
-        if kernel_compare_versions "$kernel_ver" lt $kernel_ver_min
+        if linux_compare_versions "$kernel_ver" lt $kernel_ver_min
         then
             if [ "$USE_DEBCONF" ]
             then
@@ -78,14 +172,14 @@ then
                 db_stop
             else
                 echo "ERROR: This version of the GNU libc requires kernel version"
-                echo "$kernel_ver_rec or later.  Please upgrade your kernel and reboot before installing"
-                echo 'glibc. You may need to use "apt -f install" after reboot to solve dependencies.'
+                echo "$kernel_ver_rec or later.  Please upgrade your kernel before installing"
+                echo "glibc."
                 echo
             fi
             exit 1
         fi
 
-        if kernel_compare_versions "$kernel_ver" lt $kernel_ver_rec
+        if linux_compare_versions "$kernel_ver" lt $kernel_ver_rec
         then
             if [ "$USE_DEBCONF" ]
             then
@@ -108,7 +202,7 @@ then
     then
         kernel_ver=`uname -r`
         kernel_ver_min=8.3
-        if kernel_compare_versions "$kernel_ver" lt $kernel_ver_min
+        if kfreebsd_compare_versions "$kernel_ver" lt $kernel_ver_min
         then
             if [ "$USE_DEBCONF" ]
             then
@@ -122,39 +216,8 @@ then
                 db_stop
             else
                 echo "ERROR: This version of the GNU libc requires kernel version"
-                echo "$kernel_ver_min or later.  Please upgrade your kernel and reboot before installing"
-                echo 'glibc. You may need to use "apt -f install" after reboot to solve dependencies.'
-                echo
-            fi
-            exit 1
-        fi
-
-    elif [ $system = "GNU" ]
-    then
-        kernel_ver=`uname -v | cut -d / -f 1 | cut -d ' ' -f 2`
-        kernel_ver_git=${kernel_ver#*+git}
-        kernel_ver_git=${kernel_ver_git%%-*}
-        kernel_ver=${kernel_ver%+git*}
-        kernel_ver_min=1.8
-        kernel_ver_git_min=20210923
-        if kernel_compare_versions "$kernel_ver" lt $kernel_ver_min || \
-         ( kernel_compare_versions "$kernel_ver" eq $kernel_ver_min && \
-            [ "$kernel_ver_git" -lt $kernel_ver_git_min ] )
-        then
-            if [ "$USE_DEBCONF" ]
-            then
-                db_version 2.0
-                db_fset glibc/kernel-too-old seen false
-                db_reset glibc/kernel-too-old
-                db_subst glibc/kernel-too-old kernel_ver $kernel_ver_min+git$kernel_ver_git_min
-                db_input critical glibc/kernel-too-old || true
-                db_go
-                db_stop
-            else
-                echo "ERROR: This version of the GNU libc requires kernel version"
-                echo "$kernel_ver_min+git$kernel_ver_git_min or later."
-                echo "Please upgrade your kernel and reboot before installing glibc."
-                echo 'You may need to use "apt -f install" after reboot to solve dependencies.'
+                echo "$kernel_ver_min or later.  Please upgrade your kernel before installing"
+                echo "glibc."
                 echo
             fi
             exit 1
@@ -164,10 +227,58 @@ fi
 
 if [ "$type" = upgrade ]
 then
-    if [ -n "$preversion" ] && [ -x "$(command -v ischroot)" ] && ! ischroot; then
+    # Try to detect copies of the libc library in the various places
+    # the dynamic linker uses.
+    ldfile=$(readlink -m /lib64/ld-linux-x86-64.so.2)
+    if test -f "$file"; then
+        ldbytes=$(head -c 20 /lib64/ld-linux-x86-64.so.2 | od -c)
+    else
+        # If the symlink to the dynamic linker is dangling or missing, set
+        # ldbytes to an empty string, the test below will fail and all the
+        # libraries found will be ignored.
+        ldbytes=""
+    fi
+    libcfiles=$(dpkg-query -L ${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} 2>/dev/null)
+
+    dirs="/lib/x86_64-linux-gnu /lib /lib/tls /lib32 /lib64 /usr/local/lib /usr/local/lib32 /usr/local/lib64"
+    for dir in $dirs ; do
+        check_dir "in an unexpected directory" $dir
+    done
+
+    if test -n "$LD_LIBRARY_PATH"; then
+        dirs=$(echo $LD_LIBRARY_PATH | sed 's/:/ /g')
+        for dir in $dirs ; do
+            check_dir "via LD_LIBRARY_PATH" $dir
+        done
+    fi
+
+    if test -e /etc/ld.so.conf; then
+        dirs=$(echo $(cat /etc/ld.so.conf))
+        if test -n "$dirs" ; then
+            for dir in $dirs ; do
+                check_dir "via /etc/ld.so.conf" $dir
+            done
+        fi
+    fi
+
+    if [ -e /lib/tls/i686/cmov/libc.so.6 ] || [ -e /lib/i686/cmov/libc.so.6 ] ; then
+        status_i686=$(dpkg -s libc6-i686 2>/dev/null | grep ^Status: | sed -e 's/^Status: \(.*\) \(.*\) \(.*\)/\3/g')
+        status_xen=$(dpkg -s libc6-xen 2>/dev/null | grep ^Status: | sed -e 's/^Status: \(.*\) \(.*\) \(.*\)/\3/g')
+        if ([ -z "$status_i686" ] || [ "$status_i686" = "not-installed" ] || [ "$status_i686" = "config-files" ]) && \
+             ([ -z "$status_xen" ] || [ "$status_xen" = "not-installed" ] || [ "$status_xen" = "config-files" ]); then
+            echo
+            echo "A non-dpkg owned copy of the libc6-i686 package was found."
+            echo "It is not safe to upgrade the C library in this situation;"
+            echo "please remove that copy of the C library and try again."
+            echo
+            exit 1
+        fi
+    fi
+
+    if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
 	# NSS authentication trouble guard
-	if dpkg --compare-versions "$preversion" lt 2.39; then
-	    if grep -E -q '(^|/)(xscreensaver|xlockmore)' /proc/*/cmdline 2>/dev/null; then
+	if dpkg --compare-versions "$preversion" lt 2.31; then
+	    if pidof xscreensaver xlockmore >/dev/null; then
 		if [ "$USE_DEBCONF" ] ; then
 		    db_version 2.0
 		    db_reset glibc/disable-screensaver
@@ -195,14 +306,14 @@ then
 	    fi
 
 	    check="kdm postgresql xdm"
+            # the following substitution processes the check variable
+            # and returns results in the services variable
 	    # NSS services check:
 	    	    echo -n "Checking for services that may need to be restarted..."
 	    # Only get the ones that are installed, of the same architecture
-	    # as libc (or arch all) and configured. Restart openssh-server even
-	    # if only half-configured to continue accepting new connections
-	    # during the upgrade.
+	    # as libc (or arch all) and configured
 	    [ -n "$check" ] && check=$(dpkg-query -W -f='${binary:Package} ${Status} ${Architecture}\n' $check 2> /dev/null | \
-			grep -E "(^openssh-server .* unpacked|installed) (all|${DPKG_MAINTSCRIPT_ARCH})$" | sed 's/[: ].*//')
+			grep -E "installed (all|${DPKG_MAINTSCRIPT_ARCH})$" | sed 's/[: ].*//')
 	    # some init scripts don't match the package names
 	    check=$(echo $check | \
 		    sed -e's/\bat\b/atd/g' \
@@ -211,7 +322,6 @@ then
 			-e's/\blpr\b/lpd/g' \
 			-e's/\blpr-ppd\b/lpd-ppd/g' \
 			-e's/\bmysql-server\b/mysql/g' \
-			-e's/\bopenssh-server\b/ssh/g' \
 			-e's/\bsasl2-bin\b/saslauthd/g' \
 			-e's/\bsamba\b/smbd/g' \
 			-e's/\bpostgresql-common\b/postgresql/g' \
@@ -280,32 +390,6 @@ then
 		fi
 	    fi
 
-            # As long systemd-logind has not seen any login request since the system has been
-            # booted, it has not loaded any NSS module. In that condition if glibc is upgraded
-            # (that means with a non session shell or by some automation), the NSS modules are
-            # replaced by a new major version which might be incompatible (and definitely are
-            # for some versions).
-            #
-            # The solution implemented for most daemons is to restart them, but unfortunately
-            # it is not something supported with systemd-logind (see bug#91950).
-            #
-            # As a workaround, when detected that the system is using systemd and that the
-            # systemd-logind process has not not loaded any NSS module, force systemd-logind to
-            # load NSS modules. This is done by disabling lingering on a non-existing user. This
-            # has to be done by talking directly to systemd-logind through sd-bus, as loginctl
-            # first checks if the user actually exist. The nonexistent uid is chosen as
-            # 4294967294, which is reserved by Policy §9.2.2.
-            #
-            # Note that starting with glibc 2.34, the nss_files is builtin. When glibc >= 2.34
-            # ends-up in a stable release, this workaround can therefore be dropped.
-            if dpkg --compare-versions "$preversion" lt 2.34 && [ -d /run/systemd/system ]; then
-                if ! grep -q -E 'libnss_(compat|db|files)' /proc/$(systemctl show --property MainPID --value systemd-logind.service)/maps >/dev/null 2>&1; then
-                    echo "Forcing systemd-logind to load NSS modules..."
-                    busctl call --system org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager \
-                        SetUserLinger ubb 4294967294 false false >/dev/null 2>&1 || true
-                fi
-            fi
-
             services=""
             check="apache2 apache apache-ssl apache-perl autofs at"
             check="$check boa cucipop courier-authdaemon cron cups exim"
@@ -320,11 +404,9 @@ then
             # NSS services check:
             	    echo -n "Checking for services that may need to be restarted..."
 	    # Only get the ones that are installed, of the same architecture
-	    # as libc (or arch all) and configured. Restart openssh-server even
-	    # if only half-configured to continue accepting new connections
-	    # during the upgrade.
+	    # as libc (or arch all) and configured
 	    [ -n "$check" ] && check=$(dpkg-query -W -f='${binary:Package} ${Status} ${Architecture}\n' $check 2> /dev/null | \
-			grep -E "(^openssh-server .* unpacked|installed) (all|${DPKG_MAINTSCRIPT_ARCH})$" | sed 's/[: ].*//')
+			grep -E "installed (all|${DPKG_MAINTSCRIPT_ARCH})$" | sed 's/[: ].*//')
 	    # some init scripts don't match the package names
 	    check=$(echo $check | \
 		    sed -e's/\bat\b/atd/g' \
@@ -333,7 +415,6 @@ then
 			-e's/\blpr\b/lpd/g' \
 			-e's/\blpr-ppd\b/lpd-ppd/g' \
 			-e's/\bmysql-server\b/mysql/g' \
-			-e's/\bopenssh-server\b/ssh/g' \
 			-e's/\bsasl2-bin\b/saslauthd/g' \
 			-e's/\bsamba\b/smbd/g' \
 			-e's/\bpostgresql-common\b/postgresql/g' \
@@ -349,8 +430,8 @@ then
 		fi
 	    done
 
-            if [ -n "$services" ] && [ ! -x /usr/lib/needrestart/apt-pinvoke ]; then
-                if [ "$USE_DEBCONF" ] ; then
+            if [ -n "$services" ]; then
+                if [ -f /usr/share/debconf/confmodule ] ; then
                     db_version 2.0
                     if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
                         db_input medium libraries/restart-without-asking || true
@@ -431,57 +512,23 @@ then
             else
                 echo "Nothing to restart."
             fi
-	fi # end upgrading and $preversion lt Glibc6_VERSION
+	fi # end upgrading and $preversion lt 2.31
     fi # Upgrading
-fi
 
-# We create the top-level lib symlink on merged-usr systems, so that we can
-# cover cases where for example libc6:amd64 on i386 is installed and then removed
-# (which deletes the symlink too). Note that we only suppor the simplest case,
-# no conversion (moving files) is done here, as that's the job of the usrmerge
-# package. See: https://bugs.debian.org/926699
-# Once all packages install only under /usr, this can be removed, as removing
-# this package will no longer result in the symlink being deleted.
-if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
-    if [ -L "$DPKG_ROOT/lib" ]; then
-        # Has the link already been created?
-        # If it has not, is a directory already there? Half-merged systems are
-        # the problem of usrmerge, simply ignore them here.
-        if [ ! -L "${DPKG_ROOT}/lib64" ] && [ ! -d "${DPKG_ROOT}/lib64" ]; then
-            mkdir -p "$DPKG_ROOT/usr/lib64"
-            ln -s usr/lib64 "${DPKG_ROOT}/lib64"
-        fi
-    fi
-fi
-
-# begin-remove-after: released:forky
-# Add DEP17 M4 protective diversions. These should be added by base-files, but
-# we want to avoid Pre-Depends: base-files (>= trixie) and therefore add them
-# for base-files. As bookworm's base-files installs bin lib and sbin, the only
-# directory we may miss is the one containing the runtime linker when it is not
-# /lib.
-if [ "$1" = install -o "$1" = upgrade ] && [ "/lib64" != "/lib" ]; then
-    dpkg-divert --quiet --add --no-rename --package base-files --divert "/lib64.usr-is-merged" "/lib64"
-fi
-# end-remove-after
-
-# Add DEP17 M8 protective diversions for the runtime dynamic linker. It is
-# installed in both libc (multiarch) and libc-alt (multilib) amounting to a
-# move and thus DEP17 P1 problem. This diversion should be removed by forky's
-# libc.postinst.
-if [ "$1" = install ] || [ "$1" = upgrade ]; then
-    dpkg-divert --quiet --add --no-rename --divert "/lib64/ld-linux-x86-64.so.2.usr-is-merged" "/lib64/ld-linux-x86-64.so.2"
+    # This will keep us from using hwcap libs (optimized) during an
+    # upgrade.
+    touch /etc/ld.so.nohwcap
 fi
 
 
 
 if [ -n "$preversion" ]; then
-    if dpkg --compare-versions "$preversion" lt 2.39; then
+    if dpkg --compare-versions "$preversion" lt 2.31; then
        # unconditionally wipe ld.so.cache on major version upgrades; this
        # makes those upgrades a bit slower, but is less error-prone than
        # hoping we notice every time the cache format is changed upstream
-       rm -f "$DPKG_ROOT/etc/ld.so.cache"
-       rm -f "$DPKG_ROOT/var/cache/ldconfig/aux-cache"
+       rm -f /etc/ld.so.cache
+       rm -f /var/cache/ldconfig/aux-cache
     fi
 fi
 
